# Default values for stx-lat-tool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
replicaCount: 1

image:
  repository: stx-lat-tool
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.0"

volumeMounts:
  workspace:
    name: latd-shared-workspace
    mountPath: /localdisk
  entropy:
    name: entropy-device
    mountPath: /dev/random
  patchConfig:
    name: patch-env
    mountPath: /etc/profile.d/stx-patch-env.sh
    subPath: stx-patch-env.sh

volumes:
  workspace:
    name: latd-shared-workspace
    hostPath:
      path: /localdisk
  entropy:
    name: entropy-device
    hostPath:
      path: /dev/urandom
  patchConfig:
    name: patch-env
    configMapName: lat-patch

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

dnsConfig:
  options:
    - name: ndots
      value: "1"

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
