---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stx-repomgr.fullname" . }}
  labels:
    {{- include "stx-repomgr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "stx-repomgr.selectorLabels" . | nindent 4 }}
