# Default values for stx-lat-tool.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
replicaCount: 1

image:
  repository: docker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "20.10.12-dind"

volumes:
  sharedWorkspace:
    mountPath: /localdisk
    hostPath: /localdisk
  dockerVar:
    mountPath: /var/lib/docker
    hostPath: /docker/var

services:
  dockerDaemon:
    type: ClusterIP
    port: 2375

dnsConfig:
  options:
    - name: ndots
      value: "1"

insecureRegistries:
#  - "registry.address:port"

# Pass --mtu to docker daemon
# mtu: "1410"
mtu:

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext:
  privileged: true
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
