---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stx-pkgbuilder.fullname" . }}
  labels:
    {{- include "stx-pkgbuilder.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "stx-pkgbuilder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "stx-pkgbuilder.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: true
          volumeMounts:
          - name: {{ .Values.volumeMounts.name }}
            mountPath: {{ .Values.volumeMounts.mountPath}}
          - name: {{ .Values.volumeMounts.envsetupname }}
            mountPath: {{ .Values.volumeMounts.envsetupmountPath}}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}

      volumes:
      - name: {{ .Values.volumes.name }}
        hostPath:
          path: {{ .Values.volumes.hostPath.path }}
      - name: {{ .Values.volumes.envsetupname }}
        configMap:
          name: {{ .Values.volumes.configmapname }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
