# Default values for stx-repomgr.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

---
replicaCount: 1

image:
  repository: stx-pulp
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.1.0"

volumeMounts:
  name: pulp-setting
  mountPath: /etc/pulp
  storagename: pulp-storage
  storagemountPath: /var/lib/pulp
  pgsqlname: pulp-pgsql
  pgsqlmountPath: /var/lib/pgsql
  containersname: pulp-containers
  containersmountPath: /var/lib/containers

volumes:
  name: pulp-setting
  configmapname: pulp
  storagename: pulp-storage
  storagehostPath:
    path: /pulp/pulp-storage
  pgsqlname: pulp-pgsql
  pgsqlhostPath:
    path: /pulp/pulp-pgsql
  containersname: pulp-containers
  containershostPath:
    path: /pulp/pulp-containers

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
# fsGroup: 2000

securityContext: {}
# capabilities:
#   drop:
#   - ALL
# readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000

service:
  type: ClusterIP
  port: 8080

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
# limits:
#   cpu: 100m
#   memory: 128Mi
# requests:
#   cpu: 100m
#   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
